# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4.1.6
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
         #skopeo copy docker://nextcloud/aio-nextcloud:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/nextcloud/aio-nextcloud:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-watchtower:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-watchtower:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-nextcloud:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-nextcloud:latest
         skopeo --insecure-policy copy docker://nextcloud/all-in-one:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/all-in-one:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-apache:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-apache:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-redis:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-redis:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-collabora:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-collabora:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-imaginary:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-imaginary:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-postgresql:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-postgresql:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-notify-push:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-notify-push:latest
         skopeo --insecure-policy copy docker://nextcloud/aio-domaincheck:latest docker://registry.cn-hangzhou.aliyuncs.com/keersun/aio-domaincheck:latest
 
